### ISSUE TITLE
Widget dragging and moving flaky in grid view

### ISSUE THREAD

**Issue by hoganmaps** [ozone-development/ozp-webtop#501] opened 2015-03-20 14:48 UTC
Some users are unable to drag widgets, while others are able to drag widgets (poorly) in the grid view. Might be an issue with the underlying angular gridster library we are using.

**Comment by clarkjefcoat** [comment] 2015-03-30 17:50
Duplicate of #285

**Comment by clarkjefcoat** [comment] 2015-03-31 15:54
Closing as dup

**Closed by clarkjefcoat** 2015-03-31 15:54 UTC
Labels: 0 - Backlog, duplicate
